kind: Service
apiVersion: v1
metadata:
  name: products-app-service
  labels:
    app: products-app
spec:
  selector:
    app: products-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: products-app-deployment
  labels:
    app: products-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: products-app
  template:
    metadata:
      labels:
        app: products-app
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "products-app"
        dapr.io/app-port: "5000"
    spec:
      containers:
      - name: products-app-pod
        image: us-docker.pkg.dev/hellogcp-336107/hello-gcp-app/productsapp:v0
        ports:
        - containerPort: 5000
        imagePullPolicy: Always